name: kerahbiru
description: Platform Insan Karya Raga

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.6

  # HTTP & API
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # Encryption
  crypto: ^3.0.3

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1 # untuk buka WhatsApp

  # Images
  image_picker: ^1.0.4

  # Sensors (untuk shake detection)
  sensors_plus: ^4.0.0

  # Date & Time
  intl: ^0.18.1

  # Rating
  flutter_rating_bar: ^4.0.1

  # Others
  path_provider: ^2.1.1

  # Untuk handle permissions lebih baik
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
